import forms from '@tailwindcss/forms'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#131313',
        'on-background': '#e5e2e1',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-variant': '#353534',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c2c6d6',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#8c909f',
        'outline-variant': '#424754',
        'surface-tint': '#adc6ff',
        primary: '#adc6ff',
        'on-primary': '#002e6a',
        'primary-container': '#4d8eff',
        'on-primary-container': '#00285d',
        'inverse-primary': '#005ac2',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        secondary: '#a4d64c',
        'on-secondary': '#233600',
        'secondary-container': '#719e13',
        'on-secondary-container': '#1e2f00',
        'secondary-fixed': '#bff365',
        'secondary-fixed-dim': '#a4d64c',
        'on-secondary-fixed': '#131f00',
        'on-secondary-fixed-variant': '#354e00',
        tertiary: '#ffb786',
        'on-tertiary': '#502400',
        'tertiary-container': '#df7412',
        'on-tertiary-container': '#461f00',
        'tertiary-fixed': '#ffdcc6',
        'tertiary-fixed-dim': '#ffb786',
        'on-tertiary-fixed': '#311400',
        'on-tertiary-fixed-variant': '#723600',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        // Traffic direction semantics (DESIGN.md): inbound = blue, outbound = violet.
        'traffic-in': '#5aa9ff',
        'traffic-out': '#c4a2ff',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        'display-lg': ['Inter'],
        'headline-md': ['Inter'],
        'title-md': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'label-xs': ['Inter'],
        'data-mono': ['"JetBrains Mono"'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-xs': ['11px', { lineHeight: '16px', fontWeight: '700' }],
        'data-mono': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
      spacing: {
        unit: '4px',
        gutter: '12px',
        'container-padding': '16px',
        'canvas-grid': '20px',
      },
    },
  },
  plugins: [forms],
}
